name: lamb-matricula-dev

services:
  postgres-matricula-dev:
    image: postgres:16-alpine
    container_name: lamb-postgres-matricula-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: lamb_matricula_db
      POSTGRES_USER: lamb
      POSTGRES_PASSWORD: lamb
    ports:
      - "15455:5432"
    volumes:
      - lamb_matricula_dev_data:/var/lib/postgresql/data

volumes:
  lamb_matricula_dev_data:
