CREATE TABLE IF NOT EXISTS matriculas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_persona BIGINT NOT NULL,
    periodo VARCHAR(20) NOT NULL,
    fecha TIMESTAMP NOT NULL DEFAULT now(),
    estado VARCHAR(20) NOT NULL DEFAULT 'REGISTRADA',
    PRIMARY KEY (id)
);

-- id_seccion NO lleva FOREIGN KEY: la tabla secciones vive en la base de lamb-planificacion-ms.
-- creditos acepta NULL: una sección sin validar (Circuit Breaker abierto) queda sin créditos confirmados.
CREATE TABLE IF NOT EXISTS detalle_matriculas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_matricula BIGINT NOT NULL REFERENCES matriculas(id),
    id_seccion BIGINT NOT NULL,
    creditos INTEGER,
    PRIMARY KEY (id)
);
